### ISSUE TITLE
Why not predict u,v directly to be easier?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#75]
Hi,

It seems:
1. the learned physics predict u,v,
2. change u,v to divergence and vorticity,
3. the left side of dynamical equation predicts divergence and vorticity.
4. transform div and curl to u,v
and so to loop.

Why not predict u,v in the left side of dynamical equations so that the step 2 and 4 can be delete?

**Comment by shoyer** [comment]
This would be reasonable alternative. It might simplify the equations a bit, but I don't think it would result in a major speed-up, in part because the learned physics is not calculated at every dycore timestep.

We originally implemented the dynamical core in terms of divergence and vorticity because that is the canonical formulation (e.g., in Dale Durran's textbook and SPEEDY).

**Comment by weatherforecasterwhai** [comment]
Thank you!
Found the clues at Durran's book, first said in the primitive equation,
then found the explain in 6.4.4.1: 
The main reason is u,v is not convenient to approximate into spectral series at the pole region,
because u,v are not continuous unless the wind near the pole is zero.
